services:
  cmladsb_container:
    build: .
    container_name: cmladsb_container
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://python_user:python_password@db:5432/python_db"
    volumes:
      - cmladsb_workspace:/home/python_user/workspace
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

volumes:
  cmladsb_workspace:
    driver: local
  postgres_data:
    driver: local

